version: '3.8'

services:
  queue:
    image: redis
    restart: always
    env_file:
      - ./.env
    ports:
      - '6379:6379'
    command: --loglevel warning --requirepass ${REDIS_PASS}
  db:
    image: postgres
    environment:
      - PGDATA=/data/postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/db:/data/postgres
    restart: always