version: '3.8'

services:
  queue:
    image: redis
    restart: always
    env_file:
      - ./.env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASS}
  db:
    image: postgres
    environment:
      - PGDATA=/data/postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/db:/data/postgres
    restart: always
  # app:
  #   build: ./
  #   container_name: app
  #   volumes:
  #     - type: bind
  #       source: /var/lib/app/pictures
  #       target: /data/app/pictures
  #   command: >
  #       sh -c "alembic upgrade head &&
  #              python3 main.py"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - queue
  #     - db